### ISSUE TITLE
Translation? 

### ISSUE THREAD

**Issue by ChandlerBaskins** [angular-vietnam/100-days-of-angular#13]
I know I can't provide this but it would so cool  for a translation to English. :)

**Comment by nartc** [comment]
@ChandlerBaskins We would love to "globalize" this series but with our current bandwidth, we cannot translate this to English. There are 3 of us who are organizing/writing content for each day and also recording Youtube videos (and working full time) so there isn't really much gap for us to translate the series. 

Eventually we will, if we can "recruit" more passionate people to join us, then we can make the push to English much faster. Please be patience. And thank you for your interests. 🙂

**Comment by ChandlerBaskins** [comment]
I'll keep my eye out. Thank you for all that you do!
