### ISSUE TITLE
Day 37 - Async Validator

### ISSUE THREAD

**Issue by trungk18** [angular-vietnam/100-days-of-angular#25]

**Comment by TND195** [comment]
Cho mình hỏi có giải pháp nào sau khi close dialog mới quyết định check asyncValidators không ạ?

**Comment by trungk18** [comment]
Bạn có thể nói rõ hơn được ko? 
Theo ý mình hiểu tức là có một form ở trong modal dialog. Và khi bạn close dialog thì bạn muốn làm gì?

**Comment by TND195** [comment]
Sorry vì mô tả chưa được rõ ràng :D

Ví dụ.Mình có 1 textbox khi nhập giá trị vào thì nó sẽ mở ra 1 dialog để confirm có check giá trị đó trên server không? Nếu nhấn oke thì mới chạy hàm asyncValidator, còn hủy thì sẽ không làm gì.Liệu mình có áp dụng được cái asyncValidator trong trường hợp này không?
