### ISSUE TITLE
Validate FormGroup với 1 vài control

### ISSUE THREAD

**Issue by TND195** [angular-vietnam/100-days-of-angular#27]
Mình gặp 1 trouble như sau nhưng hiện tại chưa có hướng giải quyết:
Có 1 FormGroup gồm 3 FormControl: A, B, C.Mình viết hàm asyncValidators luôn cả FormGroup nhưng mình chỉ muốn validate khi chỉ có A,B thay đổi thôi.Còn C thì không.
Có cách nào mà không cần bỏ C ra hoặc tạo FormGroup riêng cho A với B không? Tại khi get Value ra đem lên BE hơi rắc rối.

Thanks.

**Comment by tntruong96** [comment]
trong hàm validator bạn có thể chọn ra fields mình muốn để check mà. bạn kham khảo thử chổ người ta check password match với nhau trong đây: https://codinglatte.com/posts/angular/cool-password-validation-angular/

**Comment by TND195** [comment]
Nó chỉ set error thôi.Chứ mình thấy trong project khi thay đổi email nó vẫn chạy hàm validate của formGroup.Vậy nếu th async thì nó sẽ call api lên hệ thống

**Comment by trungk18** [comment]
@TND195 Mình chưa gặp trường hợp này bao giờ nhưng đơn giản nhất là như bạn nói, tạo ra một formGroup riêng cho field A và B. Rồi khi submit form thì merge formGroup chứa A,B và C thành một object thôi. Nếu ko thì phải code hơi thủ công ở hàm async validator trước khi tạo request lên server validate

**Comment by TND195** [comment]
Cảm ơn bạn.Tại mình muốn xem có giải pháp nào hay hơn không?Do nghiệp dự án gặp nhiều trường hợp thế này.Mình sợ sau này còn thêm check A, B,D thì khó bỏ trong group được.
